main: com.kyloka.forcePlugin.LightSaberPlugin
name: ForcePlugin
version: 2.0
description: Pushes other players
authors: [nayoshi12, ZlokkiN]

commands:
  lightsaber:
    description: lightsabers will be summoned